on:
  push:
    branches: [ "main" ]
jobs:
  ffufing:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: install ffuf
      run: |
        go install github.com/ffuf/ffuf/v2@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Juice in Docker
      run: docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop:latest

    - name: wait startup
      run: sh -c 'for i in $(seq 0 2 58); do curl -sSf http://localhost:3000 > /dev/null 2>&1 && exit 0; sleep 2; done; exit 1'

    - name: ffufing
      run: |
          ffuf -w sql_inj.lst \
               -u http://localhost:3000/rest/user/login \
               -X POST \
               -fc 500 \
               -H "Content-Type: application/json" \
               -d '{"email": "FUZZ", "password": "password123"}' \
               -fr "Invalid email or password" \
               -o ffuf_results.json

    - name: results
      uses: actions/upload-artifact@v4
      if: always() # сохраняем в любом случае
      with:
        name: ffuf-report
        path: ffuf_results.json

    - name: Stop and Cleanup Container
      if: always()
      run: docker stop juice-shop; docker rm juice-shop
